services:
  foo:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8501:8501
    restart: always
    develop:
      watch:
        - path: requirements.txt
          action: rebuild
        - path: .
          target: /app
          action: sync
volumes:
  app:
    external: true
